 const CONSTANTS = {
    
    currencyList : [
    { name: "Great British Pound", code: "GBP", symbol: "£", position: "prefix" },
    { name: "Afghan Afghani", code: "AFN", symbol: "؋", position: "prefix" },
    { name: "Albanian Lek", code: "ALL", symbol: "L", position: "suffix" },
    { name: "Algerian Dinar", code: "DZD", symbol: "د.ج", position: "suffix" },
    { name: "Angolan Kwanza", code: "AOA", symbol: "Kz", position: "suffix" },
    { name: "Argentine Peso", code: "ARS", symbol: "$", position: "prefix" },
    { name: "Armenian Dram", code: "AMD", symbol: "֏", position: "prefix" },
    { name: "Aruban Florin", code: "AWG", symbol: "ƒ", position: "prefix" },
    { name: "Australian Dollar", code: "AUD", symbol: "$", position: "prefix" },
    { name: "Azerbaijani Manat", code: "AZN", symbol: "₼", position: "suffix" },
    { name: "Bahamian Dollar", code: "BSD", symbol: "$", position: "prefix" },
    { name: "Bahraini Dinar", code: "BHD", symbol: ".د.ب", position: "suffix" },
    { name: "Bangladeshi Taka", code: "BDT", symbol: "৳", position: "prefix" },
    { name: "Barbadian Dollar", code: "BBD", symbol: "$", position: "prefix" },
    { name: "Belarusian Ruble", code: "BYN", symbol: "Br", position: "suffix" },
    { name: "Belize Dollar", code: "BZD", symbol: "$", position: "prefix" },
    { name: "Bermudian Dollar", code: "BMD", symbol: "$", position: "prefix" },
    { name: "Bhutanese Ngultrum", code: "BTN", symbol: "Nu.", position: "suffix" },
    { name: "Bitcoin", code: "BTC", symbol: "₿", position: "prefix" },
    { name: "Bolivian Boliviano", code: "BOB", symbol: "Bs.", position: "suffix" },
    { name: "Bosnia-Herzegovina Convertible Mark", code: "BAM", symbol: "KM", position: "suffix" },
    { name: "Botswanan Pula", code: "BWP", symbol: "P", position: "suffix" },
    { name: "Brazilian Real", code: "BRL", symbol: "R$", position: "prefix" },
    { name: "Brunei Dollar", code: "BND", symbol: "$", position: "prefix" },
    { name: "Bulgarian Lev", code: "BGN", symbol: "лв", position: "suffix" },
    { name: "Burundian Franc", code: "BIF", symbol: "FBu", position: "suffix" },
    { name: "Cambodian Riel", code: "KHR", symbol: "៛", position: "suffix" },
    { name: "Canadian Dollar", code: "CAD", symbol: "$", position: "prefix" },
    { name: "Cape Verdean Escudo", code: "CVE", symbol: "$", position: "prefix" },
    { name: "Cayman Islands Dollar", code: "KYD", symbol: "$", position: "prefix" },
    { name: "Central African CFA Franc", code: "XAF", symbol: "FCFA", position: "suffix" },
    { name: "CFP Franc", code: "XPF", symbol: "₣", position: "suffix" },
    { name: "Chilean Peso", code: "CLP", symbol: "$", position: "prefix" },
    { name: "Chinese Yuan", code: "CNY", symbol: "¥", position: "prefix" },
    { name: "Colombian Peso", code: "COP", symbol: "$", position: "prefix" },
    { name: "Comorian Franc", code: "KMF", symbol: "CF", position: "suffix" },
    { name: "Congolese Franc", code: "CDF", symbol: "FC", position: "suffix" },
    { name: "Costa Rican Colón", code: "CRC", symbol: "₡", position: "prefix" },
    { name: "Croatian Kuna", code: "HRK", symbol: "kn", position: "suffix" },
    { name: "Cuban Peso", code: "CUP", symbol: "$", position: "prefix" },
    { name: "Czech Republic Koruna", code: "CZK", symbol: "Kč", position: "suffix" },
    { name: "Danish Krone", code: "DKK", symbol: "kr", position: "suffix" },
    { name: "Djiboutian Franc", code: "DJF", symbol: "Fdj", position: "suffix" },
    { name: "Dominican Peso", code: "DOP", symbol: "$", position: "prefix" },
    { name: "East Caribbean Dollar", code: "XCD", symbol: "$", position: "prefix" },
    { name: "Egyptian Pound", code: "EGP", symbol: "£", position: "prefix" },
    { name: "Eritrean Nakfa", code: "ERN", symbol: "Nfk", position: "suffix" },
    { name: "Estonian Kroon", code: "EEK", symbol: "kr", position: "suffix" },
    { name: "Ethiopian Birr", code: "ETB", symbol: "Br", position: "suffix" },
    { name: "Euro", code: "EUR", symbol: "€", position: "prefix" },
    { name: "Falkland Islands Pound", code: "FKP", symbol: "£", position: "prefix" },
    { name: "Fijian Dollar", code: "FJD", symbol: "$", position: "prefix" },
    { name: "Gambian Dalasi", code: "GMD", symbol: "D", position: "suffix" },
    { name: "Georgian Lari", code: "GEL", symbol: "₾", position: "suffix" },
    { name: "Ghanaian Cedi", code: "GHS", symbol: "₵", position: "suffix" },
    { name: "Gibraltar Pound", code: "GIP", symbol: "£", position: "prefix" },
    { name: "Gold Ounce", code: "XAU", symbol: "Au", position: "suffix" },
    { name: "Guatemalan Quetzal", code: "GTQ", symbol: "Q", position: "suffix" },
    { name: "Guernsey Pound", code: "GGP", symbol: "£", position: "prefix" },
    { name: "Guinean Franc", code: "GNF", symbol: "FG", position: "suffix" },
    { name: "Guyanaese Dollar", code: "GYD", symbol: "$", position: "prefix" },
    { name: "Haitian Gourde", code: "HTG", symbol: "G", position: "suffix" },
    { name: "Honduran Lempira", code: "HNL", symbol: "L", position: "suffix" },
    { name: "Hong Kong Dollar", code: "HKD", symbol: "$", position: "prefix" },
    { name: "Hungarian Forint", code: "HUF", symbol: "Ft", position: "suffix" },
    { name: "Icelandic Króna", code: "ISK", symbol: "kr", position: "suffix" },
    { name: "Indian Rupee", code: "INR", symbol: "₹", position: "prefix" },
    { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp", position: "prefix" },
    { name: "Iranian Rial", code: "IRR", symbol: "﷼", position: "prefix" },
    { name: "Iraqi Dinar", code: "IQD", symbol: "ع.د", position: "suffix" },
    { name: "Israeli New Sheqel", code: "ILS", symbol: "₪", position: "suffix" },
    { name: "Jamaican Dollar", code: "JMD", symbol: "$", position: "prefix" },
    { name: "Japanese Yen", code: "JPY", symbol: "¥", position: "prefix" },
    { name: "Jersey Pound", code: "JEP", symbol: "£", position: "prefix" },
    { name: "Jordanian Dinar", code: "JOD", symbol: "د.ا", position: "suffix" },
    { name: "Kazakhstani Tenge", code: "KZT", symbol: "₸", position: "suffix" },
    { name: "Kenyan Shilling", code: "KES", symbol: "KSh", position: "suffix" },
    { name: "Kuwaiti Dinar", code: "KWD", symbol: "د.ك", position: "suffix" },
    { name: "Kyrgystani Som", code: "KGS", symbol: "лв", position: "suffix" },
    { name: "Laotian Kip", code: "LAK", symbol: "₭", position: "suffix" },
    { name: "Latvian Lats", code: "LVL", symbol: "Ls", position: "suffix" },
    { name: "Lebanese Pound", code: "LBP", symbol: "ل.ل", position: "suffix" },
    { name: "Lesotho Loti", code: "LSL", symbol: "L", position: "suffix" },
    { name: "Liberian Dollar", code: "LRD", symbol: "$", position: "prefix" },
    { name: "Libyan Dinar", code: "LYD", symbol: "ل.د", position: "suffix" },
    { name: "Lithuanian Litas", code: "LTL", symbol: "Lt", position: "suffix" },
    { name: "Macanese Pataca", code: "MOP", symbol: "MOP$", position: "suffix" },
    { name: "Macedonian Denar", code: "MKD", symbol: "ден", position: "suffix" },
    { name: "Malagasy Ariary", code: "MGA", symbol: "Ar", position: "suffix" },
    { name: "Malawian Kwacha", code: "MWK", symbol: "MK", position: "suffix" },
    { name: "Malaysian Ringgit", code: "MYR", symbol: "RM", position: "suffix" },
    { name: "Maldivian Rufiyaa", code: "MVR", symbol: "Rf", position: "suffix" },
    { name: "Mauritanian Ouguiya", code: "MRO", symbol: "UM", position: "suffix" },
    { name: "Mauritian Rupee", code: "MUR", symbol: "₨", position: "suffix" },
    { name: "Mexican Peso", code: "MXN", symbol: "$", position: "prefix" },
    { name: "Moldovan Leu", code: "MDL", symbol: "L", position: "suffix" },
    { name: "Mongolian Tugrik", code: "MNT", symbol: "₮", position: "suffix" },
    { name: "Moroccan Dirham", code: "MAD", symbol: "د.م.", position: "suffix" },
    { name: "Mozambican Metical", code: "MZN", symbol: "MT", position: "suffix" },
    { name: "Myanma Kyat", code: "MMK", symbol: "K", position: "suffix" },
    { name: "Namibian Dollar", code: "NAD", symbol: "$", position: "prefix" },
    { name: "Nepalese Rupee", code: "NPR", symbol: "₨", position: "prefix" },
    { name: "Netherlands Antillean Guilder", code: "ANG", symbol: "ƒ", position: "suffix" },
    { name: "New Taiwan Dollar", code: "TWD", symbol: "$", position: "prefix" },
    { name: "New Zealand Dollar", code: "NZD", symbol: "$", position: "prefix" },
    { name: "Nicaraguan Córdoba", code: "NIO", symbol: "C$", position: "suffix" },
    { name: "Nigerian Naira", code: "NGN", symbol: "₦", position: "suffix" },
    { name: "North Korean Won", code: "KPW", symbol: "₩", position: "suffix" },
    { name: "Norwegian Krone", code: "NOK", symbol: "kr", position: "suffix" },
    { name: "Omani Rial", code: "OMR", symbol: "ر.ع.", position: "suffix" },
    { name: "Pakistani Rupee", code: "PKR", symbol: "₨", position: "prefix" },
    { name: "Palladium Ounce", code: "XPD", symbol: "Pd", position: "suffix" },
    { name: "Panamanian Balboa", code: "PAB", symbol: "B/.", position: "suffix" },
    { name: "Papua New Guinean Kina", code: "PGK", symbol: "K", position: "suffix" },
    { name: "Paraguayan Guarani", code: "PYG", symbol: "₲", position: "suffix" },
    { name: "Peruvian Nuevo Sol", code: "PEN", symbol: "S/.", position: "suffix" },
    { name: "Philippine Peso", code: "PHP", symbol: "₱", position: "suffix" },
    { name: "Platinum Ounce", code: "XPT", symbol: "Pt", position: "suffix" },
    { name: "Polish Zloty", code: "PLN", symbol: "zł", position: "suffix" },
    { name: "Qatari Rial", code: "QAR", symbol: "ر.ق", position: "suffix" },
    { name: "Romanian Leu", code: "RON", symbol: "lei", position: "suffix" },
    { name: "Russian Ruble", code: "RUB", symbol: "₽", position: "suffix" },
    { name: "Rwandan Franc", code: "RWF", symbol: "FRw", position: "suffix" },
    { name: "Saint Helena Pound", code: "SHP", symbol: "£", position: "prefix" },
    { name: "Salvadoran Colón", code: "SVC", symbol: "$", position: "prefix" },
    { name: "Samoan Tala", code: "WST", symbol: "WS$", position: "suffix" },
    { name: "Sao Tome and Principe Dobra", code: "STD", symbol: "Db", position: "suffix" },
    { name: "Saudi Riyal", code: "SAR", symbol: "ر.س", position: "suffix" },
    { name: "Serbian Dinar", code: "RSD", symbol: "дин.", position: "suffix" },
    { name: "Seychellois Rupee", code: "SCR", symbol: "₨", position: "suffix" },
    { name: "Sierra Leonean Leone", code: "SLL", symbol: "Le", position: "suffix" },
    { name: "Silver Ounce", code: "XAG", symbol: "Ag", position: "suffix" },
    { name: "Singapore Dollar", code: "SGD", symbol: "$", position: "prefix" },
    { name: "Solomon Islands Dollar", code: "SBD", symbol: "$", position: "prefix" },
    { name: "Somali Shilling", code: "SOS", symbol: "Sh.So.", position: "suffix" },
    { name: "South African Rand", code: "ZAR", symbol: "R", position: "suffix" },
    { name: "South Korean Won", code: "KRW", symbol: "₩", position: "suffix" },
    { name: "Special Drawing Rights", code: "XDR", symbol: "SDR", position: "suffix" },
    { name: "Sri Lankan Rupee", code: "LKR", symbol: "₨", position: "suffix" },
    { name: "Sudanese Pound", code: "SDG", symbol: "ج.س.", position: "suffix" },
    { name: "Surinamese Dollar", code: "SRD", symbol: "$", position: "prefix" },
    { name: "Swazi Lilangeni", code: "SZL", symbol: "E", position: "suffix" },
    { name: "Swedish Krona", code: "SEK", symbol: "kr", position: "suffix" },
    { name: "Swiss Franc", code: "CHF", symbol: "CHF", position: "suffix" },
    { name: "Syrian Pound", code: "SYP", symbol: "£S", position: "suffix" },
    { name: "Tajikistani Somoni", code: "TJS", symbol: "ЅМ", position: "suffix" },
    { name: "Tanzanian Shilling", code: "TZS", symbol: "TSh", position: "suffix" },
    { name: "Thai Baht", code: "THB", symbol: "฿", position: "prefix" },
    { name: "Tongan Pa'anga", code: "TOP", symbol: "T$", position: "suffix" },
    { name: "Trinidad and Tobago Dollar", code: "TTD", symbol: "$", position: "prefix" },
    { name: "Tunisian Dinar", code: "TND", symbol: "د.ت", position: "suffix" },
    { name: "Turkish Lira", code: "TRY", symbol: "₺", position: "suffix" },
    { name: "Turkmenistani Manat", code: "TMT", symbol: "m", position: "suffix" },
    { name: "Ugandan Shilling", code: "UGX", symbol: "USh", position: "suffix" },
    { name: "Ukrainian Hryvnia", code: "UAH", symbol: "₴", position: "suffix" },
    { name: "United Arab Emirates Dirham", code: "AED", symbol: "د.إ", position: "suffix" },
    { name: "United States Dollar", code: "USD", symbol: "$", position: "prefix" },
    { name: "Uruguayan Peso", code: "UYU", symbol: "$U", position: "suffix" },
    { name: "Uzbekistan Som", code: "UZS", symbol: "лв", position: "suffix" },
    { name: "Vanuatu Vatu", code: "VUV", symbol: "VT", position: "suffix" },
    { name: "Venezuelan Bolívar", code: "VEF", symbol: "Bs", position: "suffix" },
    { name: "Vietnamese Dong", code: "VND", symbol: "₫", position: "suffix" },
    { name: "Yemeni Rial", code: "YER", symbol: "﷼", position: "suffix" },
    { name: "Zambian Kwacha", code: "ZMW", symbol: "ZK", position: "suffix" },
    { name: "Zimbabwean Dollar", code: "ZWL", symbol: "Z$", position: "suffix" }
],
}

export default CONSTANTS;